name: api_data_store
description: Provide a safe place to call API and handle errors. Support data observer and listener.
version: 0.0.1
homepage: https://github.com/XuanTung95/data_store.git

environment:
  sdk: ">=2.17.6 <4.0.0"

dependencies:
  future_interceptor: ^0.2.0

dev_dependencies:
  test:
